version: "3.9"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/meshless
      - JWT_SECRET=supersecretchangeme
      - PORT=8080
      - CORS_ORIGIN=*
    depends_on:
      - mongo
  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
