services:
  - type: web
    name: meshless-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # MONGODB_URI should be set manually in Render dashboard for security
      # - key: MONGODB_URI
      #   value: "Set this in Render dashboard environment variables"
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: "*"
      # Admin credentials should be set manually in Render dashboard for security
      # - key: ADMIN_EMAIL
      #   value: "Set this in Render dashboard environment variables"
      # - key: ADMIN_PASSWORD
      #   value: "Set this in Render dashboard environment variables"
      - key: POLYGON_RPC_URL
        value: https://rpc-mumbai.maticvigil.com
      - key: MESH_NETWORK_ID
        value: meshless-production
      - key: DEFAULT_REWARD_RATE
        value: "1.0"
      - key: MAX_PEER_CONNECTIONS
        value: "1000"
      - key: EMERGENCY_MESSAGE_TTL
        value: "24"
      - key: SOS_BROADCAST_RADIUS
        value: "1000"
